### ISSUE TITLE
Owner Status of the milkAsset Asset

### ISSUE THREAD

**Issue by MariLeigh** [hyperledger-labs/milk-donor#5]
This was a topic raised by Zeljko via email. I'm not exactly sure what the discussion topic is, but I wanted to create a text issue, so here we go! Ben, I've assigned this to you, but you can ignore it for now. I can't seem to assign Zeljko.

**Comment by bdjidi** [comment]
Should be good now.

**Comment by MariLeigh** [comment]
Ok, I'll close this issue then. Thanks!
